### ISSUE TITLE
Consider Gtk4 on Linux?

### ISSUE THREAD

**Issue by pubnoconst** [PolyMeilex/rfd#108]
There has been a massive update to the GTK file dialogue recently as the GTK4 file chooser dialogue finally adds support for thumbnail preview. As far as I understand GTK4 has been ported to FreeBSD as well but the next Fedora Linux release will feature the latest GTK with the new filechooser dialogue.

**Comment by Be-ing** [comment]
I think the XDG Portal backend should already use that FWIW.

**Comment by PolyMeilex** [comment]
We want to get rid of GTK altogether, so it's not worth the work (and borderline impossible with some of the changes in GTK4). On GTK3 backend, you can add `GTK_USE_PORTAL=1` env variable to make it always run via XDG Portal, or if you are writing your own app you can just disable GTK backend and run with RFD's XDG portal backend.

In case you are not familiar with XDG Portal it will essentially use whatever your DE provides, so in case of Gnome GTK4 + libadwaita file dialog, in case of KDE QT file dialog.
