### ISSUE TITLE
Opening a file dialog does nothing half of the time in Windows

### ISSUE THREAD

**Issue by vihdzp** [PolyMeilex/rfd#11]
I'm using `rfd` in a larger project. In a thread separate from the main one, I'm showing a file dialog to either open or save a file when the user clicks a button. Sometimes the file dialog shows, and I can interact with it properly. But about half of the time, the dialogs don't open at all. Here's the [link](https://github.com/OfficialURL/miratope-rs/blob/57c90e9406b0f973514b05e5eee66826e33ff4f4/src/ui/mod.rs#L61) to the line that sometimes fails. I'll try to come up with a MWE later today or tomorrow.

I had previously tried using `native-dialog`, which had a similar behavior, except that instead of silently failing, it crashed with an `ImplementationError("CoInitializeEx")` error.

I haven't been able to test this on Linux, and this fails on MacOS due to the issue of me running this outside of the main thread in the first place.

**Comment by PolyMeilex** [comment]
Thanks for report.
I will investigate it when I have time, but in the meantime:
`and this fails on MacOS due to the issue of me running this outside of the main thread in the first place.`
This sounds like a bug, rfd supports spawning dialogs from any thread as long as there is NSApp running in your program (winit starts one for sure).

**Comment by OfficialURL** [comment]
Is it really a new bug? I thought it was just the documented behavior about Sync dialogs in MacOS. Quoting from the readme:
> Macos Sync dialog freezes when used with winit (same way as `nfd`).
I haven't tried making this an async dialog, maybe that will fix this issue. I'll report back once I get it to work.

**Comment by PolyMeilex** [comment]
Oh ok, I understand now. 
`due to the issue of me running this outside of the main thread` 
I just thought that you are talking about thread-safety related problems (I believe that all of them are fixed by now) 
Winit bug in sync dialogs is not related to threading, it happens no meter how you spawn your dialog.
Async one should work as expected.
Sorry for misunderstanding

**Comment by OfficialURL** [comment]
So, should I just never use sync dialogs? Or what are the conditions that make them trigger this winit bug, and how can I avoid it?

**Comment by PolyMeilex** [comment]
As far as I know, there is no way to avoid it without [editing winit codebase](https://github.com/PolyMeilex/winit/commit/69a6129d088d0cada976e2da9d3a93954ca1f824), but I'm not winit dev, so I don't recomend this way. That's why I wrote Async dialog api

**Comment by lukors** [comment]
Don't know if this helps at all, but I had the same issue with native-dialog on Windows as you do, and oddly enough the solution I found was to deactivate Bevy's audio plugin.

**Comment by OfficialURL** [comment]
> 
> 
> Don't know if this helps at all, but I had the same issue with native-dialog on Windows as you do, and oddly enough the solution I found was to deactivate Bevy's audio plugin.

Huh, this seems to have fixed it. So, what's the underlying issue here? Libraries interfering with one another? Some bug in the underlying framework?

**Comment by PolyMeilex** [comment]
`My guess is that multiple libs are trying to initialize COM at the same time.`
Oh, so my initial guess was right. It's related to COM init, `cpal` uses multi threaded COM, and `cpal` is used by `rodio` and `rodio` is used by `bevy` to output audio.
probably it's this one:
https://github.com/RustAudio/cpal/blob/1b2469d0c1175250e1c7944b51e53f613671e987/src/host/wasapi/com.rs#L13

**Comment by Ragarnoy** [comment]
This would be the fix to the issue: https://github.com/rust-windowing/winit/pull/1524

**Comment by PolyMeilex** [comment]
> This would be the fix to the issue: https://github.com/rust-windowing/winit/pull/1524

In this case the problem originates from `cpal` not from `winit`, but yeah drag and drop in winit can also trigger it.

Relevant cpal issue:
https://github.com/RustAudio/cpal/issues/572

**Comment by PolyMeilex** [comment]
I have a great news:
https://github.com/RustAudio/cpal/pull/597
Got merged!
