### ISSUE TITLE
An iterator over picked files

### ISSUE THREAD

**Issue by r00ster91** [PolyMeilex/rfd#13]
Hello, thank you for the great library. It's working really well but I'm kind of having a problem. I have this case where it would be much more efficient for me if `rfd` provided me with an iterator over the picked files rather than immediately allocating `Vec` for me (which is what `rfd::FileDialog::pick_files` does). For example in the Linux GTK3 backend I can see that there is actually this internal iterator which seems to be just what I need. It is then abstracted away with this `collect`: 
https://github.com/PolyMeilex/rfd/blob/master/src/backend/gtk3/file_dialog/dialog_ffi.rs#L136
I can imagine there is many cases where you simply want to iterate over the results of `pick_files` once, so you don't really need to have it in a `Vec`.
Personally I'd change `pick_files` to return an `Iterator` instead because it really encourages efficiency: if you just want to iterate over it, you can do that but if you *really* want it to be in a `Vec`, you need to call `collect` yourself. I.e. more control. But I suppose it would be too much of a breaking change so maybe that should be `pick_files_iter`?
I wish I could implement this but I can only test the Linux implementation. I've done some initial work here:
https://github.com/r00ster91/rfd/commit/903679877e1c8660fdcda7901e33336e890f62e0
The Windows and macOS backends were pure guesswork and most likely don't work. How do you test them?

Additionally, adding the top-level `pick_files_iter` might also involve some challenges. I've come across some `the size for values of type X cannot be known at compilation time` errors trying to do that.

I would like your input on this. If you don't approve this, feel free to close it.

**Comment by PolyMeilex** [comment]
Hi! Thank you for interest.
Files were intentionally returned in a vec, to expose as little unsafe code to a user as possible, this way we don't have to worry about safety that much, as we control every part of the process. But exposing an iterator should be fine, not sure if it is safe to mark it send/sync yet, but I will investigate it further when I have more time.

`pick_files_iter` I don't like that name, but I don't think we have any better choices available, so let's stick with that.

As far as testing goes, I have Linux as my daily driver, for windows I use wine and dual booted windows, and for macOS I use an VM, so I can test all of those.

I will test/review your changes shortly.

**Comment by PolyMeilex** [comment]
I did some initial changes to make it build on Windows and macOS: [PolyMeilex/commits/pick_files_iter](https://github.com/PolyMeilex/rfd/commits/pick_files_iter) 

But I'm starting to wonder, do we really gain anything by adding this?
Memory footprint of a few file paths stored in a vec is miniscule, and the time it takes to alloc this vec is also really short in comparison to all the allocations that gtk/cocoa (not sure what about windows apis) does.
Could you share a use case that would benefit from this?

**Comment by r00ster91** [comment]
I think this bit of performance is worth it. From my view, I don't see any of the allocations GTK does so from my range I can only do so much and know that a `Vec` is being allocated for me so if it were an iterator it would give me a cleaner feeling. I'm trying to do the best I can basically. Additionally the API is nicer with an iterator as well. Also, while I was thinking how my code would look like with an iterator, I came across a bug that would not have happened if I had been given an iterator from the start. Ultimately you are free to decide whether this makes sense for you or not.
