### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by repi** [PolyMeilex/rfd#139]
Would it be possible to release a new version of the crate? 

The latest v0.11.4 release in May somehow didn't include #118 which was merged in April.

And there have been a couple of other relevant improvements also merged since like:
- #117 
- #123 
- #127
- #132

**Comment by PolyMeilex** [comment]
> The latest v0.11.4 release in May somehow didn't include https://github.com/PolyMeilex/rfd/pull/118 which was merged in April.

Yeah, as far as I remember that release was done as a hotfix for xdg-portal breakage on Linux, so the fix was cherry-picked from master.

Will try to prepare a full release soon.

**Comment by repi** [comment]
ah that makes sense!

> Will try to prepare a full release soon.

big thanks!

**Comment by PolyMeilex** [comment]
Sorry for the delay, 0.12 is published: https://github.com/PolyMeilex/rfd/releases
