### ISSUE TITLE
Major compilation time regression going from 1.71.0 to 1.72.0 with feature xdg-portal in release mode

### ISSUE THREAD

**Issue by lvaroqui** [PolyMeilex/rfd#149]
Upgrading my rust toolchain from 1.71 to 1.72, I noticed a major compilation time regression for rfd when compiled with `xdg-portal` feature in release mode.

Reproduction step:
`cargo build --release --timings --no-default-features --features=xdg-portal`

Here are a screenshot of the timings files (sorry can't upload html files to GitHub...):
- 1.71.0 (42.7s):
  ![1 71 0](https://github.com/PolyMeilex/rfd/assets/48593807/8b84a307-b32e-47d5-a53d-3f767ddaba34)
- 1.72.0 (675.0s):  
  ![1 72 0](https://github.com/PolyMeilex/rfd/assets/48593807/8d709cc3-9254-4384-8a2f-61d7ae1ccd76)

Env: Ubuntu 22.04

EDIT: after some more testing, the issue is gone on beta (1.73.0-beta.6)

**Comment by SamRodri** [comment]
Rust issue: rust-lang/rust#115207

Looks like they will backport the fix to 1.72.1

**Comment by PolyMeilex** [comment]
Most likely fixed in new rust version https://blog.rust-lang.org/2023/09/19/Rust-1.72.1.html

**Comment by lvaroqui** [comment]
Absolutely, sorry for duplicate...
