### ISSUE TITLE
Implement `Clone` and `Copy` for `MessageLevel` 

### ISSUE THREAD

**Issue by thenlevy** [PolyMeilex/rfd#16]
This could be useful to create objects that can produce several messages. 
```rust
struct MessageProducer {
level: MessageLevel
}

impl MessageProducer {
  fn message(&self) {
    AsyncMessageDialog::new().set_level(self.level).set_description("Hi").show(); // Can't move level out of self :( 
  }
}
```

Also, I love this crate :heart: , I was so happy to find a cross-platform solution for dialogs that would not freeze on MacOS when using winit

**Comment by PolyMeilex** [comment]
Sure, adding a clone for dialog builder would also be a nice addition. I will work on that shortly.
Thank you for your interest.

**Comment by PolyMeilex** [comment]
Done
