### ISSUE TITLE
Expose an API to set the dialog's current name

### ISSUE THREAD

**Issue by lucasfernog** [PolyMeilex/rfd#18]
RFD uses [gtk_file_chooser_set_filename](https://people.gnome.org/~desrt/gtk/html/GtkFileChooser.html#gtk-file-chooser-set-filename) on GTK (Linux), and it works great. It would be great if we could also set the current file name in the dialog, using [gtk_file_chooser_set_current_name](https://people.gnome.org/~desrt/gtk/html/GtkFileChooser.html#gtk-file-chooser-set-current-name). I'm not sure what would be the API to use on Mac/Windows though.

**Comment by PolyMeilex** [comment]
Sounds like an oversight, on MacOS and Windows those are the same for open and save dialog (at least I think so), I did not notice that GTK separates those. I will look into that shortly, I'll check other backends too, just in case.

**Comment by PolyMeilex** [comment]
Addressed in nonbraking `0.4.2` release.

Like GTK docs suggests, If file already exists it will use `set_filename`, if file is new it will use `set_current_name`. Let me know if that behavior is fine for your use case, if so we can close this. 

Thank you for report!

**Comment by lucasfernog** [comment]
I'll test this today, seems like it's exactly what I needed!
