### ISSUE TITLE
Not dialog appeared, return none

### ISSUE THREAD

**Issue by Dangerise** [PolyMeilex/rfd#193]
I have installed both `gnome` and `i3` on my endeavours os, and rfd works well on gnome, but there was no dialog appears when I am using i3

**Comment by PolyMeilex** [comment]
In `i3` you probably have a broken XDG Portal setup, either fix it, or install `zenity` and it should act as a fallback

**Comment by Dangerise** [comment]
@PolyMeilex solved now, I don't know why, but after I replaced nautilus with thunar as the default file manager , it worked well
