### ISSUE TITLE
MessageDialog::show undocumented

### ISSUE THREAD

**Issue by emilk** [PolyMeilex/rfd#20]
[MessageDialog::show](https://docs.rs/rfd/0.4.3/rfd/struct.MessageDialog.html#method.show) returns a `bool` but doesn't explain it.

PS: thanks for a great library!

**Comment by PolyMeilex** [comment]
It is true when dialog is accepted: 
- In `Ok` dialog, it will be true when `OK` was pressed 
- In `OkCancel` dialog, it will be true when `OK` was pressed 
- In `YesNo` dialog, it will be true when `Yes` was pressed 

Indeed, this is not obvious I will add a doc for this (it looks like the whole `MessageDialog` does not have any docs, so I will add all the other methods too, while at it)

**Comment by PolyMeilex** [comment]
Addresed in: https://github.com/PolyMeilex/rfd/commit/11c9c95677b36105832c476b516864cc5e7b3072
