### ISSUE TITLE
regression on 0.14.x?

### ISSUE THREAD

**Issue by 0323pin** [PolyMeilex/rfd#201]
Hi,
I'm using `simp`, https://github.com/Kl4rry/simp which uses `rfd` to provide Gtk file chooser to, _e.g._ open files using _File -> Open_ or, save files using _File -> Save as_

`simp`-v3.5.2 used `rfd`-v0.13.0 and the referred actions were working as expected. `simp`-v3.5.3 use `rfd`-v0.14.x and using `Ctrl+O` of _File -> Open_ don't bring-up the Gtk file chooser, nothing happens on these actions.

Is this a known regression? Apparently, it doesn't seem to affect builds where `features = ["xdg-portal"]` is used, _i.e._ Linux.

Additional information:
OS: NetBSD current
Rust: 1.78.0 source build.

**Comment by PolyMeilex** [comment]
`xdg-portal` is the default in 0.14, gtk backend will be removed, as it's a horible unsafe and broken mess. Perhaps try to install zenity if such a thing exists on bsd. RFD will try to call zenity whenever the portal is not avalible or broken.

**Comment by 0323pin** [comment]
We do have `zenity`, albeit at v3.41

When is the gtk backend removal planned?

**Comment by 0323pin** [comment]
@PolyMeilex Ok, let's close this for now, I've temporarily fixed the issue with `simp` apllying the following patch:

```
$NetBSD: patch-Cargo.toml,v 1.1 2024/06/11 08:36:49 pin Exp $

RFD crate changed the default features from Gtk to xdg-desktop-portal.
This breaks functionality on NetBSD. Restore the Gtk feature for now.

--- Cargo.toml.orig	2024-06-11 06:29:01.483993198 +0000
+++ Cargo.toml
@@ -48,7 +48,7 @@ wgpu = { version = "0.19.1", features = 
 winit = { version = "0.29.10", features = ["rwh_05"] }
 
 [target.'cfg(not(linux))'.dependencies]
-rfd = "0.14.0"
+rfd = { version = "0.14.0", default-features = false, features = ["gtk3"] }
 
 [target.'cfg(linux)'.dependencies]
 rfd = { version = "0.14.0", default-features = false, features = ["xdg-portal"] }
```

I would still appreciate any info as of when you intend to fully drop Gtk support, This gives us time to work on `xdg-desktop-portal` package and hopefully be able to support that,
Thanks!

**Comment by 0323pin** [comment]
Thanks.
I'll test zenity and let you know.
