### ISSUE TITLE
`set_directory` doesn't seem to change starting directory (Windows)

### ISSUE THREAD

**Issue by zohnannor** [PolyMeilex/rfd#22]
This code:

```rust
FileDialog::new()
        .set_directory(PathBuf::from("C:\\"))
        .pick_folder()
```

opens my Documents directory for some reason

**Comment by PolyMeilex** [comment]
Does `std::env::current_dir()` (used like in `simple` example) work for you?

For me 
```rs
rfd::FileDialog::new().set_directory("C:\\").pick_folder();
```
Works as expected in wine, I will check in a Windows VM some time later today

**Comment by zohnannor** [comment]
Nope, any path I set as default, opens C:\Users\USER\Documents\. I will test this code on another windows machine to check if error only occurs on mine.

**Comment by PolyMeilex** [comment]
In nfd code I noticed this comment:
```c
// Could also call SetDefaultFolder(), but this guarantees defaultPath -- more consistency across API.
    dialog->SetFolder( folder );
```
rfd uses setDefaut at the moment, I will add the second approach and I will let you know when it's ready for testing

**Comment by zohnannor** [comment]
Ok, waiting for an update!

P.S. I've checked the example code on another machine, it works. Apparently the issue is with my main machine; maybe I will try to figure out what leads to this error...

**Comment by PolyMeilex** [comment]
You can try master branch, I implemented the change in https://github.com/PolyMeilex/rfd/commit/1696de83f026df7f8cfb50d00cc531f8862d6445

**Comment by zohnannor** [comment]
It works now on both machines! Newest commit https://github.com/PolyMeilex/rfd/commit/11c9c95677b36105832c476b516864cc5e7b3072. I think you can release 0.4.4 now :)

**Comment by PolyMeilex** [comment]
Thank you very much for help!

I will release a patch release shortly

**Comment by zohnannor** [comment]
Thank you for quick fix!
