### ISSUE TITLE
[Windows] Dialog doesn't work if set_directory() path doesn't exist

### ISSUE THREAD

**Issue by KarlitosVII** [PolyMeilex/rfd#24]
Hello,
If `set_directory()` path doesn't exist then the dialog doesn't show up, at least on Windows.
Since rfd returns an `Option` instead of a `Result` users may assume that the dialog cannot fail, so I think it could be useful to check if the folder exist before.

Cheers.

**Comment by PolyMeilex** [comment]
Hi!
Yeah, I kinda regret that I went with `Option<R>` instead of `Result<Option<R>>`, but I don't want to break the API that much, it is a change that would affect every user.

So your suggestion is to just ignore `set_directory` when the path does not exist, right?

**Comment by KarlitosVII** [comment]
Yep.
I don't know for Linux / Mac but for Windows I think `set_directory` should be ignored in that case because the dialog silently fail and it's difficult to understand what's going on.
I had to test directly [this file](https://github.com/PolyMeilex/rfd/blob/master/src/backend/win_cid/file_dialog/dialog_ffi.rs#L143-L164) to understand that it requires an existing path.

**Comment by PolyMeilex** [comment]
Sure I will add that. In the long run I will probably add logging to the crate, so that should help a little with error/warning propagation.

Thanks for the report!
