### ISSUE TITLE
Document Linux dependencies

### ISSUE THREAD

**Issue by sourcebox** [PolyMeilex/rfd#27]
While using the GitHub CI, I found out that some Linux dependencies have to be installed:
- libpango1.0-dev 
- libatk1.0-dev 
- libgtk-3-dev

Please put this info somewhere in the README.

**Comment by PolyMeilex** [comment]
In our CI it only installs GTK, as GTK depends on ATK and Pango.

**Comment by sourcebox** [comment]
Good to know. I'm not so familiar with these details.

**Comment by PolyMeilex** [comment]
Done, thanks for the report!
