### ISSUE TITLE
use XDG Desktop Portal on Linux

### ISSUE THREAD

**Issue by Be-ing** [PolyMeilex/rfd#36]
Using [XDG Desktop Portal](https://github.com/flatpak/xdg-desktop-portal) would solve two problems. It would automatically use the desktop environment's dialog, plus it would let rfd work in Flatpak sandboxes. IIUC this could be done with the [dbus crate](https://crates.io/crates/dbus). If the portal isn't available, the old GTK implementation could be used as a fallback, but I think that should be turned into a Cargo feature to remove this crate's dependency on GTK.

**Comment by PolyMeilex** [comment]
GTK supports XDG desktop portal by default, I use it to publish one of my apps as Flatpack.
But yeah, we could implement our own dbus version, probably using zbus crate, in case someone dos not want to depend on GTK.

**Comment by Be-ing** [comment]
>  in case someone dos not want to depend on GTK

I think this would be quite common. I intend on distributing my application as a Flatpak. It would be silly to require the GNOME Flatpak runtime just for a file picker dialog.

**Comment by Be-ing** [comment]
Hmm, apparently the Freedesktop Flatpak runtime has GTK3, so I suppose this wouldn't make a difference with regard to packaging Rust applications in Flatpaks. However it would still be good to remove the dependency on GTK.

**Comment by Be-ing** [comment]
Alternatively this could use the [zbus crate](https://crates.io/crates/zbus) which is a pure Rust library for dbus.

**Comment by PolyMeilex** [comment]
> But yeah, we could implement our own dbus version, probably using zbus crate, in case someone dos not want to depend on GTK.

Yep, that was my plan already :wink:

**Comment by Be-ing** [comment]
I just found out about the [ashpd](https://lib.rs/crates/ashpd) crate which provides a nice Rust API for the XDG Desktop Portal using zbus. I'll work on using that crate to implement this.

**Comment by PolyMeilex** [comment]
Oh, that's a great find! I totally forgot about its existence.

**Comment by Be-ing** [comment]
I don't know what to do to implement the generic message dialog stuff with the XDG Desktop Portal... nor am I interested in that functionality because I can use the GUI library I'm already using (SixtyFPS) to do that. I can think of a few ways to handle this, in order of my preferences:

1. Move the message dialog code to a separate crate.
2. Put the message dialog code behind a Cargo feature.
3. Abuse the [notifications](https://docs.rs/ashpd/latest/ashpd/desktop/notification/index.html) of the XDG Desktop Portal for this... not sure if that could really work.
4. Use XDG Desktop Portal for the file dialog and GTK for the message dialog. That would kinda defeat the purpose for me because I want to remove the dependency on GTK from my application.

**Comment by PolyMeilex** [comment]
Yeah, it makes sense, there is no point in placing msg dialogs behind desktop portal.

RFD already has differences depending on the platform, all of those are noted in docs, and for example sync dialogs are behind conditional compilation because wasm does not support them.

My idea would be to simply not compile message module when xdg desktop portal feature is enabled, and document it property to let the user know what are the downsides of using this backend of rfd.

**Comment by Be-ing** [comment]
> message module

The message dialog code is within the `dialog` module currently. Shall I start with a PR to move it to its own module? Or a submodule of `dialog`?

**Comment by PolyMeilex** [comment]
Yeah sure, we can split it to two modules, backends already follow this convention, so it makes sense to do the same for dialog module

**Comment by Be-ing** [comment]
I think I'm in over my head here... ashpd only has an async API, but I can't use `await` to implement AsyncFilePickerDialogImpl because [async fn is still not supported for traits](https://github.com/rust-lang/rfcs/issues/2739). I suppose this library could run its own async executor... which seems like an ugly hack that might not compose well with whatever executor the application using this library is running. I don't understand how async libraries can be composed with this limitation.

**Comment by PolyMeilex** [comment]
Not sure if I follow, why do we need async trait fn here? Can't we just return `impl Future<>` like we do for every other backend?
I'll have a closer look at ashpd tomorrow, but I'm pretty sure it's not a problem `async fn` is just a syntax sugar around Futures.

Something like this:
```rs
 pub fn pick_file(self) -> impl Future<Output = Option<File>> {
        async move {
                whatever().await
        }
 }
 ```
 Or this:
 Something like this:
```rs
 pub fn pick_file(self) -> impl Future<Output = Option<File>> {
       inner()
 }
 
 fn async inner() -> Option<File> {
         whatever().await
 }
 ```
 Should be enough.
 
 Or am I missing an important piece of the puzzle somewhere?

**Comment by Be-ing** [comment]
Ah, thanks for the tip. This is getting somewhere now:

```rust
impl AsyncFilePickerDialogImpl for FileDialog {
    fn pick_file_async(self) -> DialogFutureType<Option<FileHandle>> {
        Box::pin(async {
            // ...
        })
    }
}
```
