### ISSUE TITLE
pick_folder not closing on Windows

### ISSUE THREAD

**Issue by fenhl** [PolyMeilex/rfd#4]
rfd 0.2.0

When clicking on the Save button in a Windows dialog created by `AsyncFileDialog::pick_folder`, the dialog remains open and the `Future` does not complete. This issue does not happen with `pick_file`, and is also not present on macOS.

**Comment by PolyMeilex** [comment]
I'm unable to reproduce this, both in wine and on real Windows machine.
I'm using modified [async example](https://github.com/PolyMeilex/rfd/blob/master/examples/async.rs) for this.
Any ideas what could be different in your setup, that would make it reproducible?
Also, could you let me know if said example works for you? (I just replaced `pick_file` with `pick_folder`), if it does then we can try to narrow down the codebase conditions for this to occur.

(I'm assuming that we are talking about win10)

**Comment by fenhl** [comment]
So it turns out I was actually using `save_file` instead of `pick_folder`, a bug introduced while adding the workaround for #3. With `pick_folder`, it behaves correctly again.
