### ISSUE TITLE
`FileDialog::set_parent` not supported on macOS

### ISSUE THREAD

**Issue by probablykasper** [PolyMeilex/rfd#53]
The doc comment for `FileDialog::set_parent` says it supports mac and windows, but this doesn't seem to be the case.

I tried switching `AsyncFileDialog` to `FileDialog` in the winit example, and the file dialog did not attach to the window.

In [file_dialog.rs](https://github.com/PolyMeilex/rfd/blob/6ca088a376a03372f8019440640fe84476d5ee26/src/backend/macos/file_dialog.rs), `self.parent` is only used for the `AsyncFileDialog` impls.

**Comment by probablykasper** [comment]
Still an issue on 0.8.0

**Comment by PolyMeilex** [comment]
As far as I remember it's limitation of the api, those "parented" dialogues that attach to the window don't have an sync equivalent.

**Comment by probablykasper** [comment]
Is it possible by using a completion handler?

Not 100% sure if this is the right one, but the docs for [beginSheet(_:completionHandler:)](https://developer.apple.com/documentation/appkit/nswindow/1419653-beginsheet) say this
> You can call this method from synchronous code using a completion handler, as shown on this page, or you can call it as an asynchronous method that has the following declaration:
> 
> ```swift
> func beginSheet(_ sheetWindow: NSWindow) async -> NSApplication.ModalResponse
> ```

**Comment by m11m** [comment]
https://github.com/PolyMeilex/rfd/pull/58
