### ISSUE TITLE
Select multiple directories at once?

### ISSUE THREAD

**Issue by martpie** [PolyMeilex/rfd#68]
Hello 👋 

I have very little experience with Rust, so I apologize in advance if I'm going to say dumb things.

I come from this [Tauri bug](https://github.com/tauri-apps/tauri/issues/4091#event-6575135004) I have reported this afternoon, is it possible to select multiple directory at once using this library?

**Comment by PolyMeilex** [comment]
Should be done today :+1: 
Just testing some stuff, to make sure that there are no regressions
