### ISSUE TITLE
Have more buttons in MessageDialog 

### ISSUE THREAD

**Issue by meowtec** [PolyMeilex/rfd#81]
It is common to have three buttons in a dialog:
![Screenshot 2022-08-11 234333](https://user-images.githubusercontent.com/4006436/184174235-219d8b2d-1cf8-4381-b3c0-fe4f4b4fc158.png)

**Comment by zphixon** [comment]
[I have a fork adding yes/no/cancel buttons](https://github.com/zphixon/rfd) for Linux and Windows. It needs some polish (macOS implementation and some extra thinking about what should be the result of pressing a custom button) but it works for yes/no/cancel dialogs.
