### ISSUE TITLE
Does the message dialog work on a second thread?

### ISSUE THREAD

**Issue by Kl4rry** [PolyMeilex/rfd#86]
MacOS generally wants UI stuff to be run on the main thread. Is it possible to create a dialog on another thread then the main thread? If  not is it possible to create it on the main thread the move it to a second thread and wait for the user response there? My use case requires awaiting a prompt repsonse without blocking the main thread.

**Comment by Kl4rry** [comment]
The second way i outlined works.

**Comment by PolyMeilex** [comment]
Yes MacOS requires UI to run on main thread, but if you have event loop running it's super easy to just schedule stuff to run on main thread, as event loop controls the main thread (is blocking it). So tldr is as long as you have winit running you have NSApplication loop running as well and RFD will make use of it to redirect stuff to main thread.

To quote docs: `RFD can run dialogs from any thread but it is only possible in a windowed app`
