### ISSUE TITLE
[Wasm32] `save_file()`

### ISSUE THREAD

**Issue by ousia** [PolyMeilex/rfd#88]
@PolyMeilex,

congratulations for your excellent work with the `rfd` library.

Will `save_file()` be implemented in `rfd` for Wasm32?

Sorry if my question is stupid, but I’m only an average user (no coding abilities) and my question comes from ruffle-rs/ruffle#7596.

Many thanks for your help.

**Comment by Masterchef365** [comment]
Looking for this as well, does anyone know of an alternative solution? Thanks!

**Comment by PolyMeilex** [comment]
Basically there is no established API for this.

HTML5 way of doing this is creating a <a> tag with the file encoded inside of it. But that requires users to supply the file contents upfront which is not how it works on native.

There is also a chrome specific API that lets you open a file save dialog and get a file handle that way, this aligns with how paths work on native so we would just have to wrap those in a new type.

**Comment by Easyoakland** [comment]
Is there a reason that a new node can't be created like the save picker which uses this kind of code?:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0">
    <title>Document</title>
    <script>
      function download(text, name, type) {
        var a = document.getElementById("a");

        var file = new Blob([text], {
          type: type
        });
        a.href = URL.createObjectURL(file);
        a.download = name;
      }
    </script>
  </head>
  <body>
    <a id="a">click here to download your file</a>
    <button onclick="download('file text', 'myfilename.txt', 'text/plain')">Create file</button>
  </body>
</html>
```
https://stackoverflow.com/questions/13405129/create-and-save-a-file-with-javascript

**Comment by Easyoakland** [comment]
@PolyMeilex It is already the case that `AsyncFileDialog` has a special `read()` method to makes accessing contents of a file uniform across targets. Is there a reason that a similar thing can't be done with something like a `write()` method?

In native and Wasm targets it would take a `Vec<u8>`. In native it would then use [`BufWriter::write_all`](https://doc.rust-lang.org/std/io/struct.BufWriter.html#method.write_all) and in wasm it would create a script node, text node, and button node such as [^1] which would prompt a download picker when clicked:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0">
    <title>Document</title>
    <script>
      function download(text, name, type) {
        var a = document.getElementById("a");

        var file = new Blob([text], {
          type: type
        });
        a.href = URL.createObjectURL(file);
        a.download = name;
      }
    </script>
  </head>
  <body>
    <a id="a">click here to download your file</a>
    <button onclick="download('file text', 'myfilename.txt', 'text/plain')">Create file</button>
  </body>
</html>
```
[^1]: https://stackoverflow.com/questions/13405129/create-and-save-a-file-with-javascript
