### ISSUE TITLE
The "simple" example does not work on Windows 10 

### ISSUE THREAD

**Issue by francesco-cattoglio** [PolyMeilex/rfd#9]
If I try to execute the command `cargo run --example simple` on Windows, no dialog is shown and the output is always `The user choose: None`.
This is because of the `.set_directory(&"/")` line, which messes things up. I did not investigate the exact reason, but I guess it has to do with that path being invalid under Windows.

This is a really minor thing but maybe it should be fixed so that newbie potential library users are not scared away from the lib.

**Comment by PolyMeilex** [comment]
You are right, there is no such thing as `/` on windows, I will probably replace it with current dir or something along those lines
