### ISSUE TITLE
XDG is not used by default

### ISSUE THREAD

**Issue by Doomsdayrs** [PolyMeilex/rfd#99]
During my work on https://github.com/ruffle-rs/ruffle/issues/9220 , I noticed that XDG is not used by default. Can this behavior be modified for proper desktop integration?

**Comment by PolyMeilex** [comment]
Well there are two ways to always use XDG Desktop Portal, either use XDG portal backend of rfd (behind feature flag as not every system has proper desktop portal setup), or just set `GTK_USE_PORTAL=1` env variable, or run your app under Flatpack.

So the only solution would be to set GTK_USE_PORTAL env variable inside of rfd.

**Comment by Doomsdayrs** [comment]
What systems do not use xdg?

**Comment by Doomsdayrs** [comment]
The behavior is stated with this, defaulting to gtk3. https://github.com/PolyMeilex/rfd/blob/f565c622e343d0f21ea7d4134b55a4527955b9db/Cargo.toml#L14

I may be misunderstanding something here, but can it not just check for XDG existing or not?

**Comment by PolyMeilex** [comment]
Yes, but switching to XDG Portal means no file dialog at all for anyone not running one of the available desktop portals.

**Comment by Doomsdayrs** [comment]
So there is no way to just load the gtk3 backend when portals are not available? 

And who is not using XDG portals?

**Comment by PolyMeilex** [comment]
> So there is no way to just load the gtk3 backend when portals are not available?

Setting `GTK_USE_PORTAL=1` would result in the same behavior, GTK would be used only as a fallback.

> And who is not using XDG portals?

Sadly, WM users usually don't, same goes for people who don't like this so-called "dbus bloat". My hope is that over time apps like browsers will drop their fallbacks and then people will simply be forced to have portals on their systems, and then we can happily drop the GTK backend all together in favor of a lot cleaner and better XDG portal backend.

**Comment by Doomsdayrs** [comment]
Thank you for explaining the situation better! I understand, and I'll close this for now. May the future be better for us all!

**Comment by PolyMeilex** [comment]
Done
